{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "k8s-sre-lab.namespace" . }}
  labels:
    {{- include "k8s-sre-lab.labels" (dict "ctx" . "component" "api") | nindent 4 }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurityEnforce | quote }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurityEnforce | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurityEnforce | quote }}
{{- end }}
