{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "k8s-sre-lab.name" . }}
  namespace: {{ include "k8s-sre-lab.namespace" . }}
  labels:
    {{- include "k8s-sre-lab.labels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "k8s-sre-lab.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
{{- end }}
