{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-sre-lab.name" . }}
  namespace: {{ include "k8s-sre-lab.namespace" . }}
  labels:
    {{- include "k8s-sre-lab.labels" (dict "ctx" . "component" "metrics") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-sre-lab.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      scheme: http
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: false
{{- end }}
