#!/usr/bin/env python3
"""Keep the pinned versions and docs/versions.md in step with upstream.

Three modes:

    --write   regenerate docs/versions.md from tools/versions.env (no network)
    --check   fail if docs/versions.md is not exactly what --write would produce (CI gate)
    --fetch   query the upstream release APIs, rewrite tools/versions.env and
              docs/versions.md (used by the weekly maintenance workflow)

The network lookups are deliberately boring: the stable Kubernetes version from
dl.k8s.io and the latest GitHub release of each tool. `--fetch` never edits the CI
workflows or the scripts, because those read tools/versions.env - one file to change,
one place to get it wrong.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
VERSIONS_ENV = REPO_ROOT / "tools" / "versions.env"
VERSIONS_DOC = REPO_ROOT / "docs" / "versions.md"

GITHUB_RELEASE_URL = "https://api.github.com/repos/%s/releases/latest"
KUBERNETES_STABLE_URL = "https://dl.k8s.io/release/stable.txt"

# key -> (release repository, label used in docs, where the pin is consumed)
TOOLS: List[Tuple[str, str, str, str]] = [
    (
        "KUBERNETES_VERSION",
        "",
        "Kubernetes API version used by kubeconform",
        "scripts/validate.sh, scripts/audit.py",
    ),
    (
        "KIND_VERSION",
        "kubernetes-sigs/kind",
        "kind (cluster used by the E2E job)",
        ".github/workflows/ci.yml",
    ),
    (
        "KUBECONFORM_VERSION",
        "yannh/kubeconform",
        "kubeconform (schema validation)",
        "scripts/install-tools.sh, scripts/validate.sh",
    ),
    (
        "KUBE_LINTER_VERSION",
        "stackrox/kube-linter",
        "kube-linter (policy validation)",
        "scripts/install-tools.sh, scripts/validate.sh",
    ),
    (
        "KUSTOMIZE_VERSION",
        "kubernetes-sigs/kustomize",
        "kustomize (overlay rendering)",
        "scripts/install-tools.sh, scripts/render.py",
    ),
    (
        "HELM_VERSION",
        "helm/helm",
        "Helm (chart lint/template)",
        "scripts/install-tools.sh, scripts/validate.sh",
    ),
    (
        "SHELLCHECK_VERSION",
        "koalaman/shellcheck",
        "shellcheck (scripts/*.sh)",
        "scripts/install-tools.sh, .github/workflows/ci.yml",
    ),
]

DEFAULT_ORDER = [
    "KUBERNETES_VERSION",
    "KIND_VERSION",
    "KIND_NODE_IMAGE",
    "KUSTOMIZE_VERSION",
    "KUBECONFORM_VERSION",
    "KUBE_LINTER_VERSION",
    "HELM_VERSION",
    "SHELLCHECK_VERSION",
    "APP_IMAGE_TAG",
]


def parse_env(text: str) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def read_env() -> Dict[str, str]:
    return parse_env(VERSIONS_ENV.read_text(encoding="utf-8"))


def write_env(values: Dict[str, str]) -> None:
    header = VERSIONS_ENV.read_text(encoding="utf-8").split("\n")
    comment_block = []
    for line in header:
        if line.startswith("#") or not line.strip():
            comment_block.append(line)
        else:
            break
    body = "\n".join("%s=%s" % (key, values[key]) for key in DEFAULT_ORDER if key in values)
    VERSIONS_ENV.write_text(
        "\n".join(comment_block).rstrip("\n") + "\n\n" + body + "\n", encoding="utf-8"
    )


def render_versions_md(values: Dict[str, str]) -> str:
    """The document is generated, so the pins and the prose can never disagree."""
    lines = [
        "# Pinned versions",
        "",
        "Generated by `scripts/update_versions.py` from [`tools/versions.env`](../tools/versions.env).",
        "Do not edit this file by hand: the weekly maintenance workflow regenerates it and",
        "`make test` fails if it is stale.",
        "",
        "| Component | Pinned version | Where it is used |",
        "| --- | --- | --- |",
    ]
    for key, _repo, label, used_by in TOOLS:
        lines.append("| %s | `%s` | `%s` |" % (label, values.get(key, "?"), used_by))
    lines += [
        "| kind node image | `%s` | `scripts/e2e-kind.sh` (kind create cluster --image) |"
        % values.get("KIND_NODE_IMAGE", "?"),
        "| demo API image tag | `%s` | `manifests/base/deployment.yaml`, `chart/values.yaml` |"
        % values.get("APP_IMAGE_TAG", "?"),
        "",
        "## How the pins are refreshed",
        "",
        "The scheduled `maintenance` workflow runs `scripts/update_versions.py --fetch`, which asks",
        "`dl.k8s.io/release/stable.txt` for the current stable Kubernetes version and the GitHub",
        "release API for each tool above. It then rewrites `tools/versions.env`, regenerates this",
        "file and re-runs the full validation (`scripts/validate.sh` plus the pytest suite) before",
        "committing anything. If validation fails, the job keeps the old pins and opens an issue",
        "with the literal tool output instead of committing a broken bump.",
        "",
        "The Helm pin deliberately stays on the 3.x line while the chart declares",
        "`apiVersion: v2`; moving to a new Helm major is a deliberate change, not a scheduled one.",
        "",
    ]
    return "\n".join(lines)


def detect_drift(values: Dict[str, str]) -> Dict[str, str]:
    """Return the entries whose upstream version differs from the pin."""
    changes: Dict[str, str] = {}

    latest_k8s = fetch_text(KUBERNETES_STABLE_URL).strip()
    if latest_k8s and latest_k8s != values.get("KUBERNETES_VERSION"):
        changes["KUBERNETES_VERSION"] = latest_k8s

    for key, repo, _label, _used in TOOLS:
        if not repo:
            continue
        try:
            payload = json.loads(fetch_text(GITHUB_RELEASE_URL % repo))
        except (urllib.error.URLError, ValueError) as error:
            print("warning: could not query %s (%s)" % (repo, error), file=sys.stderr)
            continue
        tag = payload.get("tag_name", "")
        if not tag:
            continue
        if key == "HELM_VERSION" and not tag.startswith("v3."):
            # Stay on the 3.x line; a Helm major upgrade is a deliberate change.
            continue
        if key == "KUSTOMIZE_VERSION":
            tag = tag.split("/")[-1]
        if tag != values.get(key):
            changes[key] = tag
        if key == "KIND_VERSION":
            node_image = parse_node_image(payload.get("body", ""))
            if node_image and node_image != values.get("KIND_NODE_IMAGE"):
                changes["KIND_NODE_IMAGE"] = node_image

    return changes


NODE_IMAGE_RE = re.compile(r"kindest/node:(v[0-9]+\.[0-9]+\.[0-9]+@sha256:[0-9a-f]{64})")


def parse_node_image(release_body: str) -> Optional[str]:
    """kind publishes the pre-built node image (with digest) in its release notes."""
    match = NODE_IMAGE_RE.search(release_body or "")
    return "kindest/node:%s" % match.group(1) if match else None


def fetch_text(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "k8s-sre-lab-versions"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate docs/versions.md")
    group.add_argument("--check", action="store_true", help="fail if docs/versions.md is stale")
    group.add_argument("--fetch", action="store_true", help="query upstream and bump the pins")
    args = parser.parse_args()

    values = read_env()

    if args.check:
        expected = render_versions_md(values)
        actual = VERSIONS_DOC.read_text(encoding="utf-8") if VERSIONS_DOC.exists() else ""
        if expected != actual:
            print(
                "docs/versions.md is stale; run scripts/update_versions.py --write", file=sys.stderr
            )
            return 1
        print("docs/versions.md is in step with tools/versions.env")
        return 0

    if args.write:
        VERSIONS_DOC.parent.mkdir(parents=True, exist_ok=True)
        VERSIONS_DOC.write_text(render_versions_md(values), encoding="utf-8")
        print("wrote %s" % VERSIONS_DOC.relative_to(REPO_ROOT))
        return 0

    changes = detect_drift(values)
    if not changes:
        print("no upstream drift detected")
        return 0
    for key, value in sorted(changes.items()):
        print("bump %s: %s -> %s" % (key, values.get(key), value))
        values[key] = value
    write_env(values)
    VERSIONS_DOC.parent.mkdir(parents=True, exist_ok=True)
    VERSIONS_DOC.write_text(render_versions_md(values), encoding="utf-8")
    print("updated tools/versions.env and docs/versions.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
